### ISSUE TITLE
Tool deleting/not saving corrections

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/tradeValidationTool#3]
As occurred about two weeks ago, we have again identified that the tool is deleting/not saving corrections. The analyst stated that he made many corrections for Kazakhstan that disappeared out of the table (corrections made for sunflower seed 2012-13, linseed 2012, horses 2011-12, casein 2011, malt 2011, chickens 2013-14). Any information on the cause of the glitch or when it is resolved is appreciated.

**Comment by chrmongeau** [comment]
Hopefully this was fixed. I'll wait for feedback on this to close it.

In the long term, `corrections_table` should be an actual dataset, preferably stored directly on SWS.

**Comment by chrmongeau** [comment]
#5 was fixed and the other issues with this seem to have been fixed.
