### ISSUE TITLE
Tool not deleting corrections, synchronization doesn't work either

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/tradeValidationTool#5]
Issue identified twice today by two different analysts. Tool does not allow analysts to delete corrections, and synchronize table doesn't solve the problem. Latest is pasted below:
![image](https://user-images.githubusercontent.com/31275016/30032597-22ea30ce-9197-11e7-91ad-5b234dba6419.png)

**Comment by baldwinkl** [comment]
Issue identified again today by analyst Valdivia. Despite following the steps elaborated (highlight row, click delete, click synchronize table), she was not able to delete any corrections out of the table.

![image](https://user-images.githubusercontent.com/31275016/30169785-a9b20a98-93ed-11e7-97da-4f5439092741.png)

**Comment by chrmongeau** [comment]
This is fixed now. You still have to "Synchronise table" after you click on "Delete selected correction". I don't know if this (a second click) is that useful anymore, so it may go away in the future.
