### ISSUE TITLE
Tool does not open before 8:30am

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/tradeValidationTool#6]
Not sure if this is related to the server or whatnot, but it for some reason does not function before that time.

**Comment by chrmongeau** [comment]
I just had a look at the logs, and you are right: it didn't open before 8:30. However, logs are not useful in this case as they just end with "Execution halted" without other details. Anyway, the reported issue seems not to be specific to some given time (e.g., before 8:30). The frequency of logs (from 2017-07-31 to 2017-09-05) with "Execution halted" in them says that the most common time with this kind of failure is around 18:30 (seven times). Below the top 20:

```
grep -l 'Execution halted' /var/log/shiny-server/outliers-shiny-* | sed 's/.*-\([0-9]\{2\}\)\([0-9]\)[0-9]\{3\}-.*/\1:\20/' | uniq -c | sort -nr | head -20
      7 18:30
      5 17:10
      5 15:20
      5 13:50
      4 17:50
      4 16:30
      4 16:20
      4 10:10
      4 09:40
      4 09:40
      3 18:20
      3 17:20
      3 17:00
      3 13:30
      3 13:20
      3 09:50
      3 09:40
      3 09:20
      3 09:10
      3 08:50
```

**Comment by chrmongeau** [comment]
Closing this as I didn't find a pattern (see above) that confirms that something is not making the tool work before 8:30 a.m.

**Comment by baldwinkl** [comment]
Ok...what are we supposed to do when this occurs in future? Contact you?

**Comment by chrmongeau** [comment]
Please, keep an eye on it and try to see if it actually happens constantly before 8:30. As you can see above, it doesn't seem so. If what you found persists, then we need to contact Team F.
