### ISSUE TITLE
Bug in the plots function

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/tradeValidationTool#7]
Today at 11:22, analyst Del Bello reported that the plot function has a bug, where sometimes when the correction that is applied, the plot shows the old series line as black, and the new series line as red. This occurred with a value measurement factor correction. He reports that the same error has occurred a few times before.
![image](https://user-images.githubusercontent.com/31275016/30159094-c97fc200-93c7-11e7-8956-76d1f5a1451e.png)

**Comment by chrmongeau** [comment]
Unfortunately I cannot replicate. I just did this (of course, correction was not saved):

* reporter: Albania
* partner: India
* item: seeds for planting
* flow: import
* correction -> year: 2013, type: value (Expert knowledge)

The initial graph is the following:

![image](https://user-images.githubusercontent.com/10231857/30164326-7093f200-93dc-11e7-9b97-c59ffff9f6d0.png)

After the correction it is:

![image](https://user-images.githubusercontent.com/10231857/30164313-60fc15d4-93dc-11e7-84ff-f895fa3ebb0e.png)

Thus, everything works as expected. If you can send me a way to replicate the observed behaviour, I'll be happy to have a look at it.

**Comment by chrmongeau** [comment]
Sorry, I didn't read carefully and missed "a value measurement factor correction". In any case, even with this kind of correction, I can't reproduce. See below (follows the previous example).

![image](https://user-images.githubusercontent.com/10231857/30165046-e31d40ae-93de-11e7-8ccc-8a81d28d3dee.png)

**Comment by baldwinkl** [comment]
The specific example was for Belarus imports of other forage products ne from Russia. A value measurement factor correction of 0.1 replicated this error for me. 

Marcella last week had the same problem for Italy. The correction has since been processed, but here is the screenshot:

For Italy imports of jute, raw or retted from Bulgaria, when the value is divided by 10, the unit value graph black series becomes the red one and vice versa:
![image](https://user-images.githubusercontent.com/31275016/30166971-341e9b5a-93e5-11e7-9b5d-5743d0dc501e.png)

**Comment by chrmongeau** [comment]
Yes, confirmed. Identified what is causing this: https://github.com/SWS-Methodology/tradeValidationTool/blob/4fde428b9385ac53d6f962827222815b1f8579d7/app.R#L2514

**Comment by chrmongeau** [comment]
Fixed:

https://github.com/SWS-Methodology/tradeValidationTool/blob/abd935db18307903459aa251351e4b660ec0407d/app.R#L2464
